dist: bionic
language: ruby
cache: bundler
sudo: required # needed for chrome
services:
  - postgresql
addons:
  chrome: stable
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database futurekids_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rspec

