defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: future_kids_development

test:
  <<: *defaults
  database: future_kids_test

production:
  <<: *defaults
  database: future_kids_production

